worldName: christmas
gameSpawn:

readyStateDuration: 2400
progressStateDuration: 42000
finishedStateDuration: 240

victoryScore: 1000

bonusPercentage: 0.3
bonusEvents:
  - 10000
  - 22000
  - 34000
  - 40000

clicksPerFetch_normal: 5
scorePerFetch_normal: 10
capacityInFetches_normal: 1

clicksPerFetch_special: 50
scorePerFetch_special: 100
capacityInFetches_special: 5
promptInterval_special: 1200

lootProbability_club: 0.25
lootProbability_booster: 0.3

stealerScore: 80

giftSpawnerLocations: []