worldName: world

readyStateDuration: 6000
progressStateDuration: 36000
finishedStateDuration: 200

giftBatches:
  - type: NORMAL
    time: 20
    amount: 100
  - type: SPECIAL
    time: 6000
  - type: NORMAL
    time: 12000
    amount: 75
  - type: SPECIAL
    time: 18000
  - type: NORMAL
    time: 24000
    amount: 50
  - type: SPECIAL
    time: 30000

bonusPercentage: 0.5
bonusEvents:
  - 10000
  - 22000
  - 34000

clicksPerFetch_normal: 5
scorePerFetch_normal: 10
capacityInFetches_normal: 1

clicksPerFetch_special: 15
scorePerFetch_special: 10
capacityInFetches_special: 10
promptInterval_special: 1200

stealerScore: 50

giftSpawnerLocations: []