name: MCZJUChristmas
version: 1.0.0
main: io.lazysheeep.mczjuchristmas.MCZJUChristmas
description: Plugin for the Christmas celebration of MCZJU
author: LazySheeep
api-version: '1.19'

permissions:
  permission.op:
    default: op
  permission.nop:
    default: not op

commands:
  testcmd:
    description: "test command"
    usage: "/testcmd"
    permission: permission.op