name: GiftHunting
version: '${version}'
main: io.lazysheeep.gifthunting.GiftHunting
description: Plugin for the gift-hunting game
author: LazySheeep
api-version: '1.21'

depend:
  - LazuliUI

softdepend:
  - Multiverse-Core