name: Christmas
version: 1.0.0
main: io.lazysheeep.mczju.christmas.Christmas
description: Plugin for the Christmas celebration of MCZJU
author: LazySheeep
api-version: '1.19'

permissions:
  permission.op:
    default: op
  permission.nop:
    default: not op

commands:
  christmas:
    description: "command of plugin Christmas"
    usage: |
      /christmas  get spawner   --- print locations of gift spawners
                      setter    --- give player Gift Spawn Setter
      
                  spawn all             --- spawn gift at every gift spawn
                        <spawn_amount>  --- randomly spawn <spawn_amount> gifts
      
                  event start   --- start the game
                        end     --- end the game
                        stats   --- print event stats
    aliases: [chris, christmas]
    permission: permission.op