name: GiftHunting
version: 1.0.0
main: io.lazysheeep.gifthunting.GiftHunting
description: Plugin for the gift-hunting game
author: LazySheeep
api-version: '1.19'

depend:
  - LazuliUI

permissions:
  gifthunting.player:
    description: the player of gifthunting game
    default: true
  gifthunting.op:
    description: give access to gifthunting commands and receive debug messages
    default: op

commands:
  gifthunting:
    description: "command of plugin GiftHunting"
    usage: |
      /gifthunting  get setter    --- get item giftSpawnSetter
                        booster   --- get item booster
                        club      --- get item club
                    clear spawner   --- clear all the spawner
                          gift      --- clear all the gifts
                          untracked --- clear all untracked gifts
                    stats   --- print game stats
                    start   --- start the game
                    end     --- end the game
                    pause   --- pause the game
                    unpause --- unpause the game
                    setspawn  --- set game spawn
    aliases: [gh, gifthunting]
    permission: gifthunting.op