name: GiftHunting
version: 1.0.0
main: io.lazysheeep.gifthunting.GiftHunting
description: Plugin for the gift-hunting game
author: LazySheeep
api-version: '1.19'

permissions:
  gifthunting.player:
    description: the player of gifthunting game
    default: true
  gifthunting.op:
    description: give access to gifthunting commands and receive debug messages
    default: op

commands:
  gifthunting:
    description: "command of plugin GiftHunting"
    usage: |
      /gifthunting  get spawner   --- print locations of gift spawners
                      setter    --- give player Gift Spawn Setter
      
                  spawn all             --- spawn gift at every gift spawn
                        <spawn_amount>  --- randomly spawn <spawn_amount> gifts
      
                  event start   --- start the game
                        end     --- end the game
                        stats   --- print event stats
    aliases: [gh, gifthunting]
    permission: gifthunting.op